import React from "react";
import "./colour-options.css";
import ColourInput from "./ColourInput";

export default function ColourOptions() {
	return (
		<div className="flex flex-wrap flex-row w-full gap-2 mt-2 justify-start items-start">
			<ColourInput
				value="black"
				className="bg-black"
			/>
			<ColourInput
				value="white"
				className="bg-white"
			/>
			<ColourInput
				value="gray"
				className="bg-gray-600"
			/>
			<ColourInput
				value="brown"
				className="bg-orange-950"
			/>
			<ColourInput
				value="red"
				className="bg-[rgb(255,0,0)]"
			/>
			<ColourInput
				value="orange"
				className="bg-orange-600"
			/>
			<ColourInput
				value="yellow"
				className="bg-yellow-400"
			/>
			<ColourInput
				value="lime"
				className="bg-lime-500"
			/>
			<ColourInput
				value="green"
				className="bg-green-500"
			/>
			<ColourInput
				value="emerald"
				className="bg-emerald-500"
			/>
			<ColourInput
				value="teal"
				className="bg-teal-500"
			/>
			<ColourInput
				value="cyan"
				className="bg-cyan-500"
			/>
			<ColourInput
				value="sky"
				className="bg-sky-500"
			/>
			<ColourInput
				value="blue"
				className="bg-blue-6"
			/>
			<ColourInput
				value="indigo"
				className="bg-indigo-700"
			/>
			<ColourInput
				value="purple"
				className="bg-purple-800"
			/>
			<ColourInput
				value="fuchsia"
				className="bg-fuchsia-700"
			/>
			<ColourInput
				value="pink"
				className="bg-pink-600"
			/>
		</div>
	);
}
